In [1]:
from simulation.model import PathFindingModel
import mesa
import analytics.ranking_measures as measures
import pandas as pd

In [9]:
params = {"width":20,
          "height":40,
          "obs_num":40,
          "goal_locs":['[(10,32),(8,35),(12,38)]','[(8,35),(12,38),(10,32)]','[(12,38),(10,32),(8,35)]'],
          "path_planning_alg":[0,1,2],
          "obs_weights":['1000,1000','1000,0.1','0.1,0.1','0.1,1000']}
results = mesa.batch_run(
    PathFindingModel,
    parameters = params,
    iterations = 1,
    max_steps = 500,
    number_processes = None,
    data_collection_period = 1,
    display_progress=True,
)
results_df_e1 = pd.DataFrame(results)

100%|██████████| 36/36 [02:28<00:00,  4.11s/it]

In [10]:
results_df_e1

,RunId,iteration,Step,width,height,obs_num,goal_locs,path_planning_alg,obs_weights,seed,obstacle_used,destinations,loc
0,6,0,0,20,40,40,"[(10,32),(8,35),(12,38)]",1,"0.1,0.1",None,True,"[(10, 32), (8, 35), (12, 38)]","(10, 1)"
1,6,0,1,20,40,40,"[(10,32),(8,35),(12,38)]",1,"0.1,0.1",None,True,"[(10, 32), (8, 35), (12, 38)]","(10, 2)"
2,6,0,2,20,40,40,"[(10,32),(8,35),(12,38)]",1,"0.1,0.1",None,True,"[(10, 32), (8, 35), (12, 38)]","(10, 3)"
3,6,0,3,20,40,40,"[(10,32),(8,35),(12,38)]",1,"0.1,0.1",None,True,"[(10, 32), (8, 35), (12, 38)]","(10, 4)"
4,6,0,4,20,40,40,"[(10,32),(8,35),(12,38)]",1,"0.1,0.1",None,True,"[(10, 32), (8, 35), (12, 38)]","(10, 5)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3815,24,0,248,20,40,40,"[(12,38),(10,32),(8,35)]",0,"1000,1000",None,True,"[(12, 38), (10, 32), (8, 35)]","(12, 36)"
3816,24,0,249,20,40,40,"[(12,38),(10,32),(8,35)]",0,"1000,1000",None,True,"[(12, 38), (10, 32), (8, 35)]","(12, 36)"
3817,24,0,250,20,40,40,"[(12,38),(10,32),(8,35)]",0,"1000,1000",None,True,"[(12, 38), (10, 32), (8, 35)]","(12, 36)"
3818,24,0,251,20,40,40,"[(12,38),(10,32),(8,35)]",0,"1000,1000",None,True,"[(12, 38), (10, 32), (8, 35)]","(12, 37)"
3819,24,0,252,20,40,40,"[(12,38),(10,32),(8,35)]",0,"1000,1000",None,True,"[(12, 38), (10, 32), (8, 35)]","(12, 37)"

In [7]:
results_df_e1.to_csv('results/simulation1.csv')